service: trivial-slack-bot

provider:
  name: aws
  environment:
    SLACK_TOKEN: ${opt:token}
    SLACK_SIGNING_SECRET: ${opt:signing-secret}
  runtime: nodejs10.x
  profile: ${opt:profile}
  region: ${opt:region}
  stage: ${opt:stage}
  memorySize: 1024
  timeout: 30
  logRetentionInDays: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
      - "lambda:InvokeFunction"
      Resource:
      - "*"

plugins:
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

functions:
  app:
    handler: src/app.handler
    events:
      - http: ANY /
      - http:
          method: ANY
          path: /{any+}
